# Generated by Django 5.0.7 on 2024-08-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Date_of_Birth',
            new_name='date_of_Birth',
        ),
    ]
