# Generated by Django 5.0.7 on 2024-08-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_date_of_birth_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profileImage/no-profile.png', null=True, upload_to='profileImage'),
        ),
    ]
