# Generated by Django 5.0.7 on 2024-08-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='banner_image/')),
                ('product', models.CharField(blank=True, max_length=400, null=True)),
                ('price', models.CharField(max_length=2)),
                ('dis_price', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Banner',
            },
        ),
    ]
