# Generated by Django 5.0.7 on 2024-08-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_brand_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='c_name',
        ),
    ]
